<a href="https://colab.research.google.com/github/MartiLC/Hackaton/blob/main/Standardizzazione.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler


In [ ]:
dataset = pd.DataFrame({'var1': [1.2, 4, 6, 8, 2.3, 7],
                        'var2': ['a', 'b', 'a', 'c', 'd', 'b'],
                        'var3': ['2','4','2','7','7','6']})

In [ ]:
print(dataset)

   var1 var2 var3
0   1.2    a    2
1   4.0    b    4
2   6.0    a    2
3   8.0    c    7
4   2.3    d    7
5   7.0    b    6


In [ ]:
#da applicare solo a variabili numeriche
var1 = pd.DataFrame(preprocessing.scale(dataset['var1']))
var1.columns = ['var1']
print(var1)

       var1
0 -1.442188
1 -0.304688
2  0.507813
3  1.320313
4 -0.995313
5  0.914063


In [ ]:
dataset.join(var1, rsuffix='_std')

var1 var2 var3  var1_std
0   1.2    a    2 -1.442188
1   4.0    b    4 -0.304688
2   6.0    a    2  0.507813
3   8.0    c    7  1.320313
4   2.3    d    7 -0.995313
5   7.0    b    6  0.914063

In [ ]:
dataset_array = np.matrix(dataset)
print(dataset_array)

[[1.2 'a' '2']
 [4.0 'b' '4']
 [6.0 'a' '2']
 [8.0 'c' '7']
 [2.3 'd' '7']
 [7.0 'b' '6']]


In [ ]:
var1_array = dataset_array[:, 0]
print(var1_array)

[[1.2]
 [4.0]
 [6.0]
 [8.0]
 [2.3]
 [7.0]]


In [ ]:
var1_array_scaler = StandardScaler().fit_transform(var1_array) 
print(var1_array_scaler)

[[-1.44218809]
 [-0.30468762]
 [ 0.50781271]
 [ 1.32031304]
 [-0.9953129 ]
 [ 0.91406287]]


In [ ]:
print(var1_array)

[[1.2]
 [4.0]
 [6.0]
 [8.0]
 [2.3]
 [7.0]]


In [ ]:
scaler2 = MinMaxScaler(feature_range=(0,1))
var1_array_scaler2=scaler2.fit_transform(var1_array)
print(var1_array_scaler2)

[[0.        ]
 [0.41176471]
 [0.70588235]
 [1.        ]
 [0.16176471]
 [0.85294118]]
